### PR TITLE
enable test paths to represent packages

### PR DESCRIPTION
**Pull request by madox2**
It would be great if relative path to test could represent test's package. It is more or less analogy to Java's package system. Please, consider this feature.

### CODE REVIEW

**Comment by sodik82** [comment]
+1: it allows you to structure your tests.

**Comment by juhovh** [comment]
I had to do a manual merge, so please check that the master still works.

**Comment by madox2** [comment]
It works, thanks

**Comment by juhovh** [comment]
Released in 0.2.0, thank you

**Pull request merged**
