### PR TITLE
Allow options to be passed by config or env

### PR DESCRIPTION
**Pull request by lukewaite**
Allows options to be passed via programmatic config. Environment variables (if present) still take priority.

### CODE REVIEW

**Comment by juhovh** [comment]
This looks good, I've been planning to add it myself but great that you got to it first. I'll try to find time to test properly and merge then.

**Comment by lukewaite** [comment]
Thanks! Let me know if you encounter anything odd.. I've been using it for about a week now without issues, but am happy to make any changes needed.

**Comment by lukewaite** [comment]
Updated: Removed a dangling console.log which had been inserted for debugging. Rebased.

**Comment by juhovh** [comment]
Sorry that this took so long, I published 0.1.7 today and your patch is included.
Thank you for your help!

**Comment by lukewaite** [comment]
No worries! Thanks!

**Pull request merged**
