### PR TITLE
Use xml lib for writing xml. Use ISO timestamps. Write failure tag under test case with message.

### PR DESCRIPTION
**Pull request by palmerj3**
Following guidelines for timestamp and failure tag here: http://help.catchsoftware.com/display/ET/JUnit+Format

### CODE REVIEW

**Comment by palmerj3** [comment]
@juhovh mind having a look?

**Comment by jvah** [comment]
I'll try to check this out and possibly merge next week.

**Comment by palmerj3** [comment]
👍

**Comment by palmerj3** [comment]
@jvah let me know if you'll get a chance to look at this. Been running this on CI at Spotify now for a week if it's any consolation. Would much prefer to use the published NPM package instead of a git dependency.

**Comment by jvah** [comment]
I checked through it and this looks quite good. The timestamp format is a bit weird since it's in UTC but dropping the timezone information out of it, but there indeed seems to be quite many examples online using that format, so let's just go with it. Thank you for your contribution, I'll push this to npm as 0.3.0.

**Comment by palmerj3** [comment]
@jvah excellent thanks!

**Pull request merged**
